### ISSUE TITLE
Server breaks if someone incorrectly guesses password

### ISSUE THREAD

**Issue by TK0805** [owenashurst/agar.io-clone#519]
I made my own server thru Heroku, and whenever someone incorrectly guesses the password, the whole server shuts down. So. Is there any way to make that not happen?

**Comment by ndtuan89** [comment]
can you paste the server's log here?

**Comment by PatheticMustan** [comment]
Works every time. Every time my friend dies, he tries to log in with an incorrect password, crashing the server, and restarting everybody.

**Comment by owenashurst** [comment]
The SQL has been refactored out into its own repository for logging. It's wrapped in a .catch() to prevent the whole server shutting down after it throws an exception. Originally, this was due to the fact no MySQL server had been setup. For the sake of simplicity, it would probably make sense to use SQLLite. Please feel free to submit a PR if you fancy.

**Comment by owenashurst** [comment]
Fixed in the latest commit to master https://github.com/owenashurst/agar.io-clone/commit/d7717aa9fa2c29670985920c7783a40a143e0e9c
